name: Build Extensions

on:
  workflow_dispatch:  # Manually start a workflow
  push:
    paths:
      - 'raw/**'

jobs:
  build-extensions:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Backup existing files for comparison
        run: |
          mkdir -p /tmp/backup
          if [ -d "extensions/tapp" ]; then
            cp -r extensions/tapp/* /tmp/backup/ 2>/dev/null || true
          fi
          if [ -f "extensions/extensions.jsonl" ]; then
            cp extensions/extensions.jsonl /tmp/backup/ 2>/dev/null || true
          fi
      
      - name: Run gen.py to build extensions
        run: |
          python3 gen.py
      
      - name: Restore unchanged files
        run: |
          # Compare and restore files that haven't changed
          if [ -d "/tmp/backup" ]; then
            for file in /tmp/backup/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                if [ "$filename" = "extensions.jsonl" ]; then
                  target="extensions/extensions.jsonl"
                else
                  target="extensions/tapp/$filename"
                fi
                
                if [ -f "$target" ] && cmp -s "$file" "$target"; then
                  echo "File $filename unchanged, restoring original"
                  cp "$file" "$target"
                fi
              fi
            done
          fi
      
      - name: Commit generated files
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add extensions/tapp/ extensions/extensions.jsonl
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Auto-build extensions from raw/ changes - ${GITHUB_SHA}"
      
      - name: Push changes to repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'